CREATE TABLE "InventoryItem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" Varchar,
  "description" Text,
  "currentStock" Int,
  "reorderLevel" Int,
  "optimalStockLevel" Int,
  "leadTimeDays" Int
);

CREATE TABLE "PurchaseOrder" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventoryItemId" Int,
  "quantityOrdered" Int,
  "orderDate" Date,
  "expectedDeliveryDate" Date,
  "status" Varchar
);

CREATE TABLE "InventoryHistory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventoryItemId" Int,
  "date" Date,
  "quantityChange" Int,
  "reason" Varchar
);

ALTER TABLE "PurchaseOrder" ADD FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id");

ALTER TABLE "InventoryHistory" ADD FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id");
